# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Servizio_pb2 as Servizio__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Servizio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServizioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.deposita = channel.unary_unary(
                '/magazzino.Servizio/deposita',
                request_serializer=Servizio__pb2.Articolo.SerializeToString,
                response_deserializer=Servizio__pb2.StringMessage.FromString,
                _registered_method=True)
        self.preleva = channel.unary_unary(
                '/magazzino.Servizio/preleva',
                request_serializer=Servizio__pb2.Empty.SerializeToString,
                response_deserializer=Servizio__pb2.Articolo.FromString,
                _registered_method=True)
        self.svuota = channel.unary_stream(
                '/magazzino.Servizio/svuota',
                request_serializer=Servizio__pb2.Empty.SerializeToString,
                response_deserializer=Servizio__pb2.Articolo.FromString,
                _registered_method=True)


class ServizioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def deposita(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def preleva(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def svuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServizioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'deposita': grpc.unary_unary_rpc_method_handler(
                    servicer.deposita,
                    request_deserializer=Servizio__pb2.Articolo.FromString,
                    response_serializer=Servizio__pb2.StringMessage.SerializeToString,
            ),
            'preleva': grpc.unary_unary_rpc_method_handler(
                    servicer.preleva,
                    request_deserializer=Servizio__pb2.Empty.FromString,
                    response_serializer=Servizio__pb2.Articolo.SerializeToString,
            ),
            'svuota': grpc.unary_stream_rpc_method_handler(
                    servicer.svuota,
                    request_deserializer=Servizio__pb2.Empty.FromString,
                    response_serializer=Servizio__pb2.Articolo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'magazzino.Servizio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('magazzino.Servizio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Servizio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def deposita(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/magazzino.Servizio/deposita',
            Servizio__pb2.Articolo.SerializeToString,
            Servizio__pb2.StringMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def preleva(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/magazzino.Servizio/preleva',
            Servizio__pb2.Empty.SerializeToString,
            Servizio__pb2.Articolo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def svuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/magazzino.Servizio/svuota',
            Servizio__pb2.Empty.SerializeToString,
            Servizio__pb2.Articolo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
