# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Servizio.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Servizio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eServizio.proto\x12\tmagazzino\"\'\n\x08\x41rticolo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07product\x18\x02 \x01(\t\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xb0\x01\n\x08Servizio\x12;\n\x08\x64\x65posita\x12\x13.magazzino.Articolo\x1a\x18.magazzino.StringMessage\"\x00\x12\x32\n\x07preleva\x12\x10.magazzino.Empty\x1a\x13.magazzino.Articolo\"\x00\x12\x33\n\x06svuota\x12\x10.magazzino.Empty\x1a\x13.magazzino.Articolo\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Servizio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTICOLO']._serialized_start=29
  _globals['_ARTICOLO']._serialized_end=68
  _globals['_STRINGMESSAGE']._serialized_start=70
  _globals['_STRINGMESSAGE']._serialized_end=100
  _globals['_EMPTY']._serialized_start=102
  _globals['_EMPTY']._serialized_end=109
  _globals['_SERVIZIO']._serialized_start=112
  _globals['_SERVIZIO']._serialized_end=288
# @@protoc_insertion_point(module_scope)
