# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Statistics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Statistics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Statistics.proto\x12\tstatistic\"\x1f\n\x0eStringMessaage\x12\r\n\x05value\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\'\n\x06Sensor\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\"3\n\x0bMeanRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t2\x82\x01\n\tstatistic\x12\x35\n\ngetSensors\x12\x10.statistic.Empty\x1a\x11.statistic.Sensor\"\x00\x30\x01\x12>\n\x07getMean\x12\x16.statistic.MeanRequest\x1a\x19.statistic.StringMessaage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGMESSAAGE']._serialized_start=31
  _globals['_STRINGMESSAAGE']._serialized_end=62
  _globals['_EMPTY']._serialized_start=64
  _globals['_EMPTY']._serialized_end=71
  _globals['_SENSOR']._serialized_start=73
  _globals['_SENSOR']._serialized_end=112
  _globals['_MEANREQUEST']._serialized_start=114
  _globals['_MEANREQUEST']._serialized_end=165
  _globals['_STATISTIC']._serialized_start=168
  _globals['_STATISTIC']._serialized_end=298
# @@protoc_insertion_point(module_scope)
