# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/OrderManagment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/OrderManagment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/OrderManagment.proto\x12\tecommerce\"^\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08itemList\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t\"J\n\x08Shipment\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12#\n\torderList\x18\x03 \x03(\x0b\x32\x10.ecommerce.Order\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t2\x82\x02\n\x0eOrderManagment\x12\x38\n\x08\x61\x64\x64Order\x12\x10.ecommerce.Order\x1a\x18.ecommerce.StringMessage\"\x00\x12\x38\n\x08getOrder\x12\x18.ecommerce.StringMessage\x1a\x10.ecommerce.Order\"\x00\x12>\n\x0csearchOrders\x12\x18.ecommerce.StringMessage\x1a\x10.ecommerce.Order\"\x00\x30\x01\x12<\n\rprocessOrders\x12\x10.ecommerce.Order\x1a\x13.ecommerce.Shipment\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.OrderManagment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=41
  _globals['_ORDER']._serialized_end=135
  _globals['_SHIPMENT']._serialized_start=137
  _globals['_SHIPMENT']._serialized_end=211
  _globals['_STRINGMESSAGE']._serialized_start=213
  _globals['_STRINGMESSAGE']._serialized_end=243
  _globals['_ORDERMANAGMENT']._serialized_start=246
  _globals['_ORDERMANAGMENT']._serialized_end=504
# @@protoc_insertion_point(module_scope)
