# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import OrderManagment_pb2 as proto_dot_OrderManagment__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/OrderManagment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderManagmentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addOrder = channel.unary_unary(
                '/ecommerce.OrderManagment/addOrder',
                request_serializer=proto_dot_OrderManagment__pb2.Order.SerializeToString,
                response_deserializer=proto_dot_OrderManagment__pb2.StringMessage.FromString,
                _registered_method=True)
        self.getOrder = channel.unary_unary(
                '/ecommerce.OrderManagment/getOrder',
                request_serializer=proto_dot_OrderManagment__pb2.StringMessage.SerializeToString,
                response_deserializer=proto_dot_OrderManagment__pb2.Order.FromString,
                _registered_method=True)
        self.searchOrders = channel.unary_stream(
                '/ecommerce.OrderManagment/searchOrders',
                request_serializer=proto_dot_OrderManagment__pb2.StringMessage.SerializeToString,
                response_deserializer=proto_dot_OrderManagment__pb2.Order.FromString,
                _registered_method=True)
        self.processOrders = channel.stream_stream(
                '/ecommerce.OrderManagment/processOrders',
                request_serializer=proto_dot_OrderManagment__pb2.Order.SerializeToString,
                response_deserializer=proto_dot_OrderManagment__pb2.Shipment.FromString,
                _registered_method=True)


class OrderManagmentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def processOrders(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderManagmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.addOrder,
                    request_deserializer=proto_dot_OrderManagment__pb2.Order.FromString,
                    response_serializer=proto_dot_OrderManagment__pb2.StringMessage.SerializeToString,
            ),
            'getOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.getOrder,
                    request_deserializer=proto_dot_OrderManagment__pb2.StringMessage.FromString,
                    response_serializer=proto_dot_OrderManagment__pb2.Order.SerializeToString,
            ),
            'searchOrders': grpc.unary_stream_rpc_method_handler(
                    servicer.searchOrders,
                    request_deserializer=proto_dot_OrderManagment__pb2.StringMessage.FromString,
                    response_serializer=proto_dot_OrderManagment__pb2.Order.SerializeToString,
            ),
            'processOrders': grpc.stream_stream_rpc_method_handler(
                    servicer.processOrders,
                    request_deserializer=proto_dot_OrderManagment__pb2.Order.FromString,
                    response_serializer=proto_dot_OrderManagment__pb2.Shipment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecommerce.OrderManagment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecommerce.OrderManagment', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderManagment(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.OrderManagment/addOrder',
            proto_dot_OrderManagment__pb2.Order.SerializeToString,
            proto_dot_OrderManagment__pb2.StringMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.OrderManagment/getOrder',
            proto_dot_OrderManagment__pb2.StringMessage.SerializeToString,
            proto_dot_OrderManagment__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def searchOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ecommerce.OrderManagment/searchOrders',
            proto_dot_OrderManagment__pb2.StringMessage.SerializeToString,
            proto_dot_OrderManagment__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def processOrders(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ecommerce.OrderManagment/processOrders',
            proto_dot_OrderManagment__pb2.Order.SerializeToString,
            proto_dot_OrderManagment__pb2.Shipment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
