# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ProductManager.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ProductManager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ProductManager.proto\x12\x07manager\"\x06\n\x04\x45mpy\"\'\n\x0eSellingRequest\x12\x15\n\rserial_number\x18\x01 \x01(\x03\" \n\x07Product\x12\x15\n\rserial_number\x18\x01 \x01(\x03\"\x14\n\x03\x41\x43K\x12\r\n\x05value\x18\x01 \x01(\x08\x32k\n\x0eProductManager\x12(\n\x03\x62uy\x12\r.manager.Empy\x1a\x10.manager.Product\"\x00\x12/\n\x04sell\x12\x17.manager.SellingRequest\x1a\x0c.manager.ACK\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProductManager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPY']._serialized_start=33
  _globals['_EMPY']._serialized_end=39
  _globals['_SELLINGREQUEST']._serialized_start=41
  _globals['_SELLINGREQUEST']._serialized_end=80
  _globals['_PRODUCT']._serialized_start=82
  _globals['_PRODUCT']._serialized_end=114
  _globals['_ACK']._serialized_start=116
  _globals['_ACK']._serialized_end=136
  _globals['_PRODUCTMANAGER']._serialized_start=138
  _globals['_PRODUCTMANAGER']._serialized_end=245
# @@protoc_insertion_point(module_scope)
